<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-20T17:31:24Z" name="Suite" finished-at="2021-06-20T17:31:42Z" duration-ms="18556">
    <groups>
    </groups>
    <test started-at="2021-06-20T17:31:24Z" name="Test" finished-at="2021-06-20T17:31:42Z" duration-ms="18556">
      <class name="extent.Test1">
        <test-method signature="getgoogle()[pri:0, instance:extent.Test1@7486b455]" started-at="2021-06-20T17:31:24Z" name="getgoogle" finished-at="2021-06-20T17:31:30Z" duration-ms="6401" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getgoogle -->
      </class> <!-- extent.Test1 -->
      <class name="extent.Test3">
        <test-method signature="getfacebook()[pri:0, instance:extent.Test3@5d908d47]" started-at="2021-06-20T17:31:36Z" name="getfacebook" finished-at="2021-06-20T17:31:42Z" duration-ms="5606" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Facebook - लॉग इन या साइन अप करें] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Facebook - लॉग इन या साइन अप करें] but found [Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at extent.Test3.getfacebook(Test3.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getfacebook -->
      </class> <!-- extent.Test3 -->
      <class name="extent.Test2">
        <test-method signature="getgmail()[pri:0, instance:extent.Test2@660acfb]" started-at="2021-06-20T17:31:30Z" name="getgmail" finished-at="2021-06-20T17:31:36Z" duration-ms="6256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getgmail -->
      </class> <!-- extent.Test2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
